<a href="https://colab.research.google.com/github/Simran2404/covid_mortality_calculator/blob/master/fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.0.1+cu118


In [3]:
# introduction to tensors
# everytime we do a numerical encoding of input data it is of a tensor datatype in PyTorch
# scalar - only magnitude

scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
# scalar has no dimensions of it's own
scalar.ndim

0

In [5]:
# get tensor back as a python integer
scalar.item()

7

In [6]:
# vector - magnitude and direction
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
# vector has one dimension
vector.ndim

1

In [8]:
# vector has 2 columns and one row hence the size 2
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
# dimension of a MATRIX
MATRIX.ndim

2

In [11]:
# MATRIX has 2 columns and 2 rows hence the size 2, 2
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR - an n-dimensional array of numbers
TENSOR = torch.tensor([[[1, 2, 3],
                        [2, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 6, 9],
         [2, 4, 5]]])

In [13]:
# dimension of a TENSOR
TENSOR.ndim

3

In [14]:
# TENSOR has one 3/3 matrix
# dim = 0 is the outermost bracket
# dim = 1 is the three rows
# dim = 2 is the three columns
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
# create a random tensor of size (3, 4)
# the way many neural networks learn is that they start with tensors full of random numbers and then they adjust those random numbers to better represent the data
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7268, 0.7925, 0.3726, 0.5502],
        [0.6532, 0.4999, 0.5859, 0.2742],
        [0.4010, 0.1435, 0.6340, 0.6787]])

In [16]:
random_tensor.ndim

2

In [17]:
# create a random tensor with similar shape to an image tensor
# normally for processing images you split an image into three color channels - red, green and blue
random_image_size_tensor = torch.rand(size=(224, 224, 3))  # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
# create a tensor of all zeroes
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
# unless we specify the datatype for the tensor - pytorch normally starts off as float32
ones.dtype

torch.float32

In [22]:
# create a range of tensors and tensors-like
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# creating tensors like - creates another tensor with the same shape as the input
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
# tensor datatypes
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what dataype is the tensor (float_!6, float_32, float64)
                               device=None, # what device is your tensor on - helps us write device agnostic code[cpu, cuda]
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [25]:
# by default pytorch tensors are always float32 even if you specify a none datatype
float_32_tensor.dtype

torch.float32

In [26]:
# typecasting the float_32_tensor to a float_16 dtype
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [28]:
int_32_tensor = torch.tensor([3, 6, 8], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [29]:
float_16_tensor * int_32_tensor

tensor([ 9., 36., 72.], dtype=torch.float16)

Getting information from tensors: (tensor attributes)

1. Tensors not right datatype - can use tensor.dtype
2. Tensors not right shape - can use tensor.shape
3. Tensors not on the right device - can use tensor.device


In [30]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7521, 0.9915, 0.5187, 0.1569],
        [0.6743, 0.2687, 0.6704, 0.3509],
        [0.6162, 0.2121, 0.5455, 0.2984]])

In [31]:
# find some details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7521, 0.9915, 0.5187, 0.1569],
        [0.6743, 0.2687, 0.6704, 0.3509],
        [0.6162, 0.2121, 0.5455, 0.2984]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [32]:
# manipulating tensors
# tensor operations - addition, subtraction, multiplication(element-wise), division, matrix multiplication

tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [33]:
tensor * 10

tensor([10, 20, 30])

In [34]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [35]:
torch.mul(tensor, 10) # python built-in function

tensor([10, 20, 30])

In [36]:
torch.add(tensor, 10) # python built-in function

tensor([11, 12, 13])

In [37]:
# element-wise mulitplication

print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

# matrix multiplication/ dot-product
torch.matmul(tensor, tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


tensor(14)

In [38]:
# matrix multiplication by hand
# 1*1 + 2*2 + 3*3

# time - checks the running time of the following code
# pytorch functions are ten times faster than doing it by hand

%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 365 µs, sys: 56 µs, total: 421 µs
Wall time: 430 µs


In [39]:
# the inner dimensions must match
# resulting matrices have the shape of the outer dimensions
torch.matmul(torch.rand(3, 10), torch.rand(10, 3))

tensor([[3.0885, 2.5747, 1.8797],
        [2.8850, 1.6837, 1.3125],
        [3.2854, 2.0784, 1.4893]])

In [40]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_A.size()

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])
tensor_B.size()


torch.Size([3, 2])

In [41]:
# to fix our tensor shape issues, we can manipulate the shape of our tensors using a transpose
# a transpose switches the axes or dimensions of a given tensor
tensor_B.T
tensor_B.T.size()

torch.Size([2, 3])

In [42]:
torch.mm(tensor_A, tensor_B.T) # torch.mm is an alias for matmul

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [43]:
# finding the min, max, sum, etc (tensor aggregation)

x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [45]:
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [46]:
# finding the mean requires a tensor of float32 datatype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [47]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [48]:
# finding the positional min and max - indexes of max and min
x.argmin()

tensor(0)

In [49]:
x.argmax()

tensor(9)

commonly used methods on tensors

1. reshaping - reshapes the input tensor to a defined shape
2. view - return a view of an input tensor of a certain shape but keep the same memory
3. stacking - concatenate a sequence of tensors along a dimension (vstack(on top of each other)(hstack(side by side)
4. squeezing - remove all '1' dimensions from a tensor
5. unsqueezing - adds a '1' dimension to a target tensor
6. permute - return a view of the input with dimensions permuted(swapped) in a certain way

In [50]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [51]:
# add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [52]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [53]:
# z shares the same memory as x so changing z will change x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [54]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [55]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [56]:
# stack tensors on top of each other
x_stacked = torch.vstack([x, x, x, x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [57]:
# stack tensors on top of each other
x_stacked = torch.hstack([x, x, x, x])
x_stacked

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [58]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])
New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [59]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [60]:
# torch.permute() - rearranges the dimensions of the target tensor
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# permute the original tensor to rearrange the axis (or dimension) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [61]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

In [62]:
# indexing - selecting data from tensors

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [63]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [64]:
x[0][0] # middle bracket(dim=1)

tensor([1, 2, 3])

In [65]:
x[0][2][2] # last dimension

tensor(9)

In [66]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [67]:
# ":" selects all of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [68]:
# get all values of the 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [69]:
# get all values of the 0 dimension but only the index 1 value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [70]:
# pytorch tensors and numpy
# often times data is numpy and we wish to change it to pytorch tensors
# torch.from_numpy(ndarray)
# torch.Tensor.numpy()

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # when converting from numpy to pytorch - it reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [71]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [72]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [73]:
numpy_tensor.dtype

dtype('float32')

In [74]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [75]:
# pytorch reproducibility (trying to take random out of random)

# to reduce the randomness in neural networks and pytorch comes with the concept of a random seed
# random seed flavours the randomness
# computers are generally deterministic and not really random but pseudo random

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2343, 0.9746, 0.6915, 0.3938],
        [0.2794, 0.1593, 0.1384, 0.1576],
        [0.3639, 0.9123, 0.5048, 0.2759]])
tensor([[0.6776, 0.2884, 0.4913, 0.4511],
        [0.1196, 0.4793, 0.1889, 0.2966],
        [0.4006, 0.2786, 0.7842, 0.9722]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [76]:
RANDOM_SEED =  42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) # reset the random seed everytime you have a continuous call
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [77]:
# running tensors and pytorch objects on the GPUs (and making faster computations)
# GPUs= faster computation on numbers (CUDA+ NVIDIA hardware + pytorch)

! nvidia-smi

Wed Jun 28 17:42:03 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [78]:
# check for gpu access with pytorch

import torch
torch.cuda.is_available()

True

In [79]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [80]:
# count number of devices
torch.cuda.device_count()

1

In [81]:
# putting tensors(and models) on the gpu

tensor = torch.tensor([1, 2, 3], device = "cpu")

# tensor not on gpu
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [83]:
# move tensor to gpu
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [84]:
# if tensor is on gpu it can't be transformed to numpy because it will have device issues
tensor_on_gpu.numpy()

TypeError: ignored

In [86]:
# to fix the gpu tensor with numpy issue we will set it to the cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [87]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')